[package]
name = "journal-core"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
deadpool-postgres = "0.14.1"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
tokio-postgres = "0.7.14"
